config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config.merge(controllers: { registrations: 'registrations' })
  ActiveAdmin.routes(self)
  devise_scope :user do
    get 'users/accept_invitation/:invitation_token', to: 'registrations#respond_invitation', as: :respond_invitation
    put 'users/accept_invitation', to: 'registrations#accept_invitation', as: :accept_invitation
  end

  post 'set_league/:id', to: 'league#set', as: :set_league

  resources :teams
  resources :players

  # get :admin, to: 'admin#index'
  # scope :admin, module: :admin, as: :admin do
  #   resources :leagues do
  #     resources :teams
  #     post 'managers/add_myself', to: 'managers#add_myself'
  #     resources :managers do
  #       post :resend_invitation, to: 'managers#resend_invitation', on: :member
  #       delete :delete_invitation, to: 'managers#delete_invitation', on: :member
  #     end
  #   end
  # end

  root 'dashboard#index'

end

app/views/notifications/invite_manager.md.erb
<%= @manager %>,

**You have been invited to join the "<%= @manager.league %>" Fantasy Football League by <%= @manager.invited_by %>.**

To accept this invitation, [click here](<%= respond_invitation_url @manager.invitation_token %>) and you will be taken to the Pure Fantasy League (PFL) site where you will be able to sign in and begin building your Fantasy Football Team.

*If the link above does not work, copy and paste the following line into your browser:*

  <%= respond_invitation_url @manager.invitation_token %>


If you feel that this email was sent in error, or you are not interested in playing, simply ignore it. We won't email you again.

Thanks and welcome to PFL. You're gonna love it!