config/routes.rb
Rails.application.routes.draw do

  devise_for :users, ActiveAdmin::Devise.config.merge(controllers: { registrations: 'registrations' })
  ActiveAdmin.routes(self)
  devise_scope :user do
    get 'users/accept_invitation/:invitation_token', to: 'registrations#respond_invitation', as: :respond_invitation
    put 'users/accept_invitation', to: 'registrations#accept_invitation', as: :accept_invitation
  end

  post 'set_league/:id', to: 'league#set', as: :set_league

  resources :teams
  resources :players

  # get :admin, to: 'admin#index'
  # scope :admin, module: :admin, as: :admin do
  #   resources :leagues do
  #     resources :teams
  #     post 'managers/add_myself', to: 'managers#add_myself'
  #     resources :managers do
  #       post :resend_invitation, to: 'managers#resend_invitation', on: :member
  #       delete :delete_invitation, to: 'managers#delete_invitation', on: :member
  #     end
  #   end
  # end

  root 'dashboard#index'

end

app/views/layouts/_flashes.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<%- if signed_in? && !admin_scope? -%>
  <%- if current_league -%>
    <li class="dropdown">
      <%= link_to root_path, class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
        <%= current_league %> <span class="caret"></span>
      <%- end -%>
      <ul class="dropdown-menu">
        <%- @leagues.each do |league| -%>
          <li class="<%= 'active' if league == current_league %>">
            <%= link_to league, set_league_path(league), method: :post %>
          </li>
        <%- end -%>
      </ul>
    </li>
  <%- end -%>

  <%- if current_team -%>
    <li class="dropdown">
      <%= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do %>
        <%= current_team %> <span class="caret"></span>
      <%- end -%>
      <ul class="dropdown-menu">
        <li><%= link_to 'Edit team', [:edit, current_team] %></li>
      </ul>
    </li>
  <%- end -%>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= page_title_for_header %><%= " - #{current_league}" if !admin_scope? && current_league %></title>

    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">

    <header>
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand">
              <%= link_to 'PFL', root_path %>
            </div>
          </div>

          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <%= render admin_scope? ? 'admin/nav' : 'layouts/nav' %>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <%- if signed_in? -%>
                <li class="navbar-text"><small>Signed in as <%= link_to current_user, edit_user_registration_path %></small></li>
                <%- if current_user.try(:admin?) -%>
                  <li class="<%= 'active' if admin_scope? %>"><%= link_to "ADMIN", admin_root_path %></li>
                <% end %>
                <li><%= link_to icon('sign-out fa-lg'), destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              <%- else -%>
                <li><%= link_to icon('sign-in', 'Sign in'), new_user_session_path %></li>
              <%- end -%>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="container">
      <ol class="breadcrumb">
        <%= render_breadcrumbs tag: 'li', separator: '' %>
      </ol>
    </section>

    <main role="main" class="container">
      <%= render 'layouts/flashes' %>
      <%= yield %>
    </main>

    <footer>
      <div class="container">
        <small class="text-muted">
          <span class="pull-right">
            Problems? Something not quite right? Email <%= mail_to 'joel@developwithstyle.com' %>
          </span>
          <i>Developed with Style</i> by <%= link_to 'Joel Moss', 'https://twitter.com/joelmoss' %>
        </small>
      </div>
    </footer>

  </body>
</html>